module.exports = [
    {
        count: 1,
        title: 'Sea Ranch',
        architect: 'Charles Moore',
        year: 1963,
        address: '',
        description: "A pioneering residential development along the northern coast of California, the Sea Ranch, which features the landscape designer Lawrence Halprin, architect Charles Moore, and graphic artist Barbara Stauffacher Solomon, among many others, was an attempt at a pastoral utopia for the middle-class Bay Area intellectual. The development of the original site—and the timber-clad, shed-roofed buildings nestled within it—have deeply influenced modernist design. Key trends, such as vernacular modernism that incorporates local materials and graphic interiors, can all be traced back to this singular project. Note that the development is still a private community; those wanting to visit can access public beaches and trails or rent a house there to take advantage (the Lodge at The Sea Ranch is also due to reopen in late 2019), but visiting renters should take care to respect the rights and privacy of current homeowners.",
        location: 'Sea Ranch',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648006566/attractions/CMoore.DSC00842rt.0_rxnh22.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-123.45366652720048, 38.71516075824729],
        },
    },
    {
        count: 2,
        title: 'Portland Building',
        architect: 'Michael Graves',
        year: 1982,
        address: '1120 SW 5th Ave Portland, OR 97204',
        description: 'Considered the first major work of postmodernism when it was completed in 1982 (not to be confused with earlier, example-setting buildings like the Vanna Venturi house), the Portland Municipal Services Building exemplified the styles playful re-interpretations of classical design elements. Architect Michael Graves saw the project as a ”symbolic gesture” to reclaim design from Modernisms staid, boxy, glass-and-steel grip. Wrapped in several colors and featuring bold design flourishes—including keystones, pilasters and belvederes—the 15-story building made a case for creativity in architecture. The debate still rages on: Is such a design choice engaging recontextualization, or whimsy light on symbolism? Currently, the building is in the process of a contentious $195 million “reskinning,” which city officials say will remove, strengthen, and replace the facade; preservationists feel many of the materials used in the replacement will compromise the form and facade of the building.',
        location: 'Portland',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648045153/attractions/shutterstock_750550591.0.0_ozakqt.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-122.678675, 45.515635],
        },
    },
    {
        count: 3,
        title: 'Golden Gate Bridge',
        architect: 'Irving Morrow',
        year: 1937,
        address: 'Golden Gate Bridge San Francisco, CA',
        description: 'Even when its shrouded in the Bay Area fog, this 1.7-mile suspension bridge, arguably the most famous in the country, still attracts cyclists, crowds, and onlookers marveling at one of San Franciscos most recognizable symbols. Learn more about this infrastructure marvel at Curbed San Francisco, then plan a visit.',
        location: 'San Francisco',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648045466/attractions/shutterstock_136918865.0.0_vk0ben.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-122.478611, 37.819722],
        },
    },
    {
        count: 4,
        title: 'Hallidie Building',
        architect: 'Willis Polk',
        year: 1918,
        address: '130 Sutter Street San Francisco, CA 94104',
        description: "It may seem a little short to be the forerunner of todays skyscrapers, but when it was built in 1918, the Hallidie Building was the first of its kind with a glass facade. A recent multi-year restoration project restored a bit of the nearly century-old structures shine.",
        location: 'San Francisco',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648045918/attractions/hallillde_20.0.0.0.0_bpn9sq.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-122.40437, 37.7938628],
        },
    },
    {
        count: 5,
        title: 'SFMOMA',
        architect: 'Mario Botta and Snøhetta',
        year: 1935,
        address: '151 3rd St San Francisco, CA 94103',
        description: "According to Curbed San Francisco editor Brock Keeling, the long-anticipated expansion of one of the citys signature cultural institutions has been both an “unabashed success” and “standout in the neighborhood.” Snøhettas 10-story contoured facade, an update on the classic Mario Botta building, was inspired by San Franciscos characteristic fog and choppy Bay waters.",
        location: 'San Francisco',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648046471/attractions/30SFMOMA-facebookJumbo.0.0.0.0.0_ezcozg.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-122.4008, 37.7858],
        },
    },
    {
        count: 6,
        title: 'Space Needle',
        architect: 'John Graham & Company',
        year: 1969,
        address: 'Space Needle, 400 Broad St Seattle, WA 98109',
        description: "One of the symbols of Seattle, this space-age observation tower, built for the 1962 Worlds Fair, just completed a $100 million renovation last fall. Visitors to the local icon, whose designers left a large footprint on Seattle architecture, will be able to check out a new 360-degree observation deck, complete with a glass floor and excellent views of Mt. Rainier.",
        location: 'Seattle',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648046779/attractions/shutterstock_133656629.0.0_zwcgdm.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-122.3491, 47.6204],
        },
    },
    {
        count: 7,
        title: 'Gas Works Park',
        architect: 'Haag, Richard Haag',
        year: 1906,
        address: '2101 N Northlake Way Seattle, WA 98103',
        description: "A revolutionary creative reuse project, and a “beautiful way to remember a toxic past,” this Seattle park, designed by architect Richard Haag, reimagined a coal gasification plant on the citys waterfront as an active park and childrens play place. Landscaping and repurposing of different sections of the abandoned industrial facility have made this one of the more unique parts of the citys landscape.",
        location: 'Seattle',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648046921/attractions/Gas_Works_pano_01.0.0.0.0.0_avmmq5.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-122.335, 47.646],
        },
    },
    {
        count: 8,
        title: 'Hearst Castle',
        architect: 'Julia Morgan',
        year: 1947,
        address: '750 Hearst Castle Rd San Simeon, CA 93452',
        description: "The inspiration for Xanadu in Orson Welless classic film Citizen Kane, William Randolph Hearsts castle in San Simeon was built on family land where he would take camping trips as a child. Architect Julia Morgan designed the ranch and hilltop estate based on the newspaper tycoons eclectic tastes, including Spanish themes. La Cuesta Encantada (The Enchanted Hill) became a sprawling enterprise, complete with the nations largest private zoo, a movie theater, the Neptune Pool (which contained the façade of a Roman temple Hearst imported from Europe) and a private power plant. A perfectionist, Hearst often ordered different sections to be redesigned and rebuilt; Morgan started pitching ideas in 1915, but the project still was incomplete by the time Hearst died in 1951.",
        location: 'San Simeon',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648060293/attractions/hearst_castle.0.0.0.0.0_zjtjhp.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-121.1666, 35.6852],
        },
    },
    {
        count: 9,
        title: 'The Majestic Yosemite Hotel',
        architect: 'Gilbert Stanley Underwood',
        year: 1927,
        address: '1 Ahwahnee Drive YOSEMITE NATIONAL PARK, CA 95389',
        description: "One of the defining examples of “parkitecture,” the rustic style of design found throughout the National Park System, the Yosemite Hotel (formerly the Ahwahnee Hotel) has hosted generations of tourists. Designed by Gilbert Stanley Underwood in 1927, the building was made to match its surroundings, and reflects the natural splendor that makes Yosemite so compelling.",
        location: 'YOSEMITE NATIONAL PARK',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648060403/attractions/29771565513_efa7790397_k.0.0.0_wmmctc.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-119.57427158686735, 37.74638717394014],
        },
    },
    {
        count: 10,
        title: 'Eames House',
        architect: 'Charles and Ray Eames',
        year: 1949,
        address: '203 Chautauqua Blvd Pacific Palisades, CA 90272',
        description: "Anybody convinced that modern design means cold edges and a stark palette need only peek inside the exuberant home Ray and Charles Eames designed for themselves in 1949. Commissioned as part of Art & Architecture magazines Case Study program and placed amid a eucalyptus grove in the Pacific Palisades, the prefab exterior, a Mondrian-like assembly of off-the-shelf parts—colorful panels, glass, and steel—conceals a playful and living room. The inspiring, oft-photographed space, an artful array of toys, tchotchkes, and furniture, embodies the couples imaginative and all-encompassing design philosophy.",
        location: 'Pacific Palisades',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648060657/attractions/eames_house.0.0.0.0.0_e1h0ez.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-118.519444, 34.029722],
        },
    },
    {
        count: 11,
        title: 'Seattle Central Library',
        architect: 'LMN Architects',
        year: 2004,
        address: '1000 Fourth Avenue Seattle, Washington',
        description: "The Seattle Central Library is the flagship library of the Seattle Public Library system. The 11-story (185 feet or 56.9 meters high) glass and steel building in downtown Seattle, Washington was opened to the public on May 23, 2004. Rem Koolhaas and Joshua Prince-Ramus of OMA/LMN were the principal architects, and Magnusson Klemencic Associates was the structural engineer with Arup. Arup also provided mechanical, electrical, and plumbing engineering, as well as fire/life safety, security, IT and communications, and audio visual consulting. Hoffman Construction Company of Portland, Oregon, was the general contractor.",
        location: 'Seattle',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648127757/attractions/Seattle_sbsvtt_lkbcxe.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-122.332503, 47.606699],
        },
    },
    {
        count: 12,
        title: 'Suzzallo Library',
        architect: 'Charles H. Bebb',
        year: 1963,
        address: '4000 15th Ave NE, Seattle, WA 98195',
        description: "Suzzallo Library is the central library of the University of Washington in Seattle, and perhaps the most recognizable building on campus. It is named for Henry Suzzallo, who was president of the University of Washington until he stepped down in 1926, the same year the first phase of the library's construction was completed. The library was renamed for him after his death in 1933.",
        location: 'Seattle',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648127787/attractions/UW_Suzzallo_Library_Starbucks_BB_013_web_oyp1ys_upgazc.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-122.3084, 47.6557],
        },
    },
    {
        count: 13,
        title: 'Amazon Spheres',
        architect: 'NBBJ',
        year: 2018,
        address: '2111 7th Avenue Seattle, Washington, U.S.',
        description: "“Alexa, open the Spheres”, commanded Jeff Bezos in 2018. And with that, the Spheres, an innovative office space at Amazon headquarters, became the newest addition to Seattles modern architecture scene. Founded as a way to build a natural connection within a bustling urban environment, the Spheres serve as an oasis for employees to work and relax. In total, there are three spheres, each reaching 3-4 stories and collectively made of 620 tons of steel and 2,600 glass panes. Inside there over 40,000 plants from 30 countries, including a massive “living wall” that features 25,000 plants alone!",
        location: 'Seattle',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648171701/attractions/amazon-spheres-seattle_xsmzeh.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-122.339444, 47.615556],
        },

    },
    {
        count: 14,
        title: 'Bullitt Center',
        architect: 'Miller Hull',
        year: 2012,
        address: '1501 E Madison St Seattle, WA 98122',
        description: "Opened on Earth Day in 2003, the Bullitt Center, located in the vibrant Capitol Hill neighborhood, is first and foremost a marvel of architectural sustainability. In fact, with its 100% renewable energy model, it is considered one of the “greenest” commercial buildings in the entire world which is just what architect Robert Hull intended.",
        location: 'Seattle',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648172112/attractions/seattle-bullitt-center_nybjia.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-122.3125, 47.6143],
        },
    },
    {
        count: 15,
        title: 'Volunteer Park Conservatory',
        architect: 'John Charles Olmsted',
        year: 1912,
        address: '1400 E Galer St, Seattle, WA 98112',
        description: "Volunteer Park Conservatory, a Victorian-style greenhouse and botanical garden, is the perfect escape from the hustle and bustle of city life. Built in 1912 using 3,426 glass panes, the conservatory is as delicate as it is distinctive. It may even be a familiar sight to those across the pond as it is modeled after Londons elegant Crystal Palace. From towering tropical palms to succulent desert species, it is a relaxing space filled with a sprawling variety of plants. These species are neatly organized into five distinguished “houses”: fern, bromeliad, palm, cactus, and a seasonal collection that is rotated six times per year.",
        location: 'Seattle',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648173037/attractions/seattle-volunteer-park-conservatory_foamkm.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-122.31574, 47.6321],
        },
    },
    {
        count: 16,
        title: 'Trinity Church',
        architect: 'Henry Hobson Richardson',
        year: 1877,
        address: '206 Clarendon St, Boston, MA 02116',
        description: "One of architect Henry Hobson Richardson masterpieces, this house of worship has become an iconic example of his sturdy, striking style. It portrays a sense of massiveness through sheer size (90 million pounds of stone were used during construction) and by design, with a series of towers and rough stone walls covered in balanced, bold, ornamentation, such as the checkerboard band circling the chapel. The open interior, with murals and stained glass windows, is also a showstopper.",
        location: 'Boston',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648353695/attractions/Trinity_Church__Boston__Massachusetts_LCCN2011630431.tif_l5ps2w.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-71.075556, 42.35],
        },
    },
    {
        count: 17,
        title: 'Harvard Art Museums Expansion',
        architect: 'Renzo Piano',
        year: 2013,
        address: '32 Quincy Street Cambridge, MA 02138',
        description: "One of Renzo Piano recent cultural projects concerned a selection of galleries and museums on the Harvard campus, a stylistic mashup that managed to restore the original 1920s structures while creating a modern, unified whole.",
        location: 'Boston',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648353542/attractions/2014116-MUSEUM-slide-YXCS-jumbo_x5st5o.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-71.1147, 42.3742],
        },
    },
    {
        count: 18,
        title: 'Solomon R. Guggenheim Museum',
        architect: 'Frank Lloyd Wright',
        year: 1937,
        address: '1071 Fifth Avenue at 89th Street Manhattan, New York City',
        description: "Opened six months after Frank Lloyd Wright died in 1959, the Guggenheim met with the kind of criticisms that one might imagine the architect would delight in hearing: this incredible building was so striking, it would overshadow the art within. The apex of Wright cylindrical and circular style, this cultural center, a ribbon of concrete on the Upper East Side, descended from an earlier design for the Gordon Strong Automobile Objective and Planetarium. The open atrium and curved, spiraling floorplan created a unique viewing experience, with patrons slowly ascending towards the top of the architectural nautilus shell.",
        location: 'New York',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648350049/attractions/image.0.0.0_yt7bfs.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-73.958889, 40.783056],
        },
    },
    {
        count: 19,
        title: 'Met Breuer',
        architect: 'Beyer Blinder Belle',
        year: 2016,
        address: '945 Madison Ave New York, NY 10021',
        description: "The Metropolitan Museum of Art home for contemporary art, the former space of the Whitney Museum, showcases a daring design by Marcel Breuer, restoring the Brutalist landmark, and the architect intended patinas, to pristine condition. It is a great spot for falling in love with concrete architecture all over again.",
        location: 'New York',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648350184/attractions/160301_09-50-53_5DSR7105.0.0.0.0_ynaonb.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-73.9638, 40.7734],
        },
    },
    {
        count: 20,
        title: 'Ford Foundation Building',
        architect: 'Kevin Roche',
        year: 1967,
        address: 'Ford Foundation Building, 320 E 43rd St New York, NY 10017',
        description: "This Late Modern landmark of Midtown Manhattan, designed by Kevin Roche John Dinkeloo Associates and landscaped by Dan Kiley, created the gold standard for corporate architecture way back in 1967. The Ford Foundation home, updated in 2018, beckons visitors with its 160-foot-tall atrium, encased by walls of glass, granite, and Cor-Ten steel.",
        location: 'New York',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648350451/attractions/FordFoundationAtrium_2018_A23A5554.0.0.0_cdtx7a.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-73.971111, 40.749722],
        },
    },
    {
        count: 21,
        title: 'Empire State Building',
        architect: 'Shreve, Lamb and Harmon',
        year: 1931,
        address: 'Empire State Building New York, NY 10001',
        description: "New, taller buildings may add to the city skyline, but this 102-story Art Deco tower is still the first thing many think of when they picture a New York skyscraper. The views from the observation decks are stunning; Curbed New York has a guide to getting the most out of your visit.",
        location: 'New York',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648350605/attractions/shutterstock_553685014.0.0_omvzzt.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-73.985656, 40.748433],
        },
    },
    {
        count: 22,
        title: 'Vessel',
        architect: 'Thomas Heatherwick',
        year: 2019,
        address: '20 Hudson Yards New York, NY 10001',
        description: "A spectacle made for social media, this focal point for Manhattan new Hudson Yards mega-development, is both photogenic and polarizing, and a semi-public space still fighting for must-see status among New York City great walkable meeting spots. Visitors planning to climb the Escher-esque stairways need to register for free tickets ahead of time (check Curbed New York for all the details).",
        location: 'New York',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648350853/attractions/Vessel_with_The_Shops___Restaurant_at_Hudson_Yards_Vessel_with_view_of_Hudson_River___courtesy_of_Michael_Moran_for_Related_Oxford.0.0_jujo8r.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-74.0022, 40.7538],
        },
    },
    {
        count: 23,
        title: 'Whitney Museum of American Art',
        architect: 'Renzo Piano',
        year: 2015,
        address: '99 Gansevoort Street New York, NY 10014',
        description: "Renzo Piano's home for modern American art has been one of the most talked-about buildings in recent years since opening to the public in 2015. With four levels and 50,000 square feet of gallery space, the internal space suggests a unique kind of urban stroll, according to Curbed's architecture critic Alexandra Lange.",
        location: 'New York',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648351066/attractions/_MG_6970.0.0.0.0_stq78y.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-74.0089, 40.7396],
        },
    },
    {
        count: 24,
        title: 'Governors Island',
        architect: 'N/A',
        year: 2019,
        address: 'Governors Island New York, NY 11231',
        description: "Governors Island is not the easiest place to get to—ferries depart from Manhattan and Brooklyn Bridge Park selectively—but it is worth the extra effort. The former military base has been transformed into a 172-acre green oasis that hosts a myriad of events, artworks, and attractions that are often free. The Hills, an engineered landscape, provides a new scenic outlook and slides for visitors of all ages. Curbed New York has all the details about new events and attractions debuting this year.",
        location: 'New York',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648351291/attractions/The_Hills_Governors_Island_Timothy_Schenck_10.0.0.0.0.0_jv3qm0.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-74.016111, 40.691389],
        },
    },
    {
        count: 25,
        title: 'World Trade Center Station',
        architect: 'Santiago Calatrava',
        year: 2016,
        address: '70 Vesey Street Manhattan, New York City',
        description: "The $4 billion Oculus station house, designed by Spanish architect Santiago Calatrava, consists of white ribs that interlock high above the ground. The interior of the station house contains two underground floors, which house part of the Westfield World Trade Center mall. The transportation hub connects the various modes of transportation in Lower Manhattan, from the Fulton Center in the east to the Battery Park City Ferry Terminal in the west, and includes connections to various New York City Subway stations. It is the fifth-busiest transportation hub in the New York metropolitan area. The new station has received mixed reviews: although the hub has been praised for its design, it has also been criticized for its high costs and extended delays.",
        location: 'New York',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648351577/attractions/Oculus_World_Trade_Center_-_August_18_2016_ifl8aa.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-74.0114, 40.7115],
        },
    },
    {
        count: 26,
        title: 'John F. Kennedy Presidential Library',
        architect: 'I. M. Pei',
        year: 1979,
        address: 'Columbia Point, Boston, MA 02125',
        description: "The John F. Kennedy Presidential Library and Museum is the presidential library and museum of John Fitzgerald Kennedy (1917–1963), the 35th president of the United States (1961–1963). It is located on Columbia Point in the Dorchester neighborhood of Boston, Massachusetts, next to the University of Massachusetts at Boston, the Edward M. Kennedy Institute for the United States Senate, and the Massachusetts Archives and Commonwealth Museum. Designed by the architect I. M. Pei, the building is the official repository for original papers and correspondence of the Kennedy Administration, as well as special bodies of published and unpublished materials, such as books and papers by and about Ernest Hemingway.",
        location: 'Boston',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648352581/attractions/JFK_library_Stitch_Crop_lryyp7.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-71.034086, 42.315892],
        },
    },
    {
        count: 27,
        title: 'The Institute of Contemporary Art',
        architect: 'Diller Scofidio + Renfro',
        year: 2006,
        address: '25 Harbor Shore Dr, Boston, MA 02210',
        description: "The Institute of Contemporary Art, Boston (known locally as the ICA), built a permanent home in 2006 on the edge of the harbor in the Seaport District. Diller Scofidio + Renfro designed the contemporary building to mirror the industrial cranes that load container ships nearby. Although their work has received much critical acclaim, Bostonians are split about whether the building is a beauty or an eyesore in its privileged position along Fan Pier. Within the museum, you’ll find a provocative collection of contemporary art and a longstanding dedication to serve the Boston community with stellar programming.",
        location: 'Boston',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648352954/attractions/Institute_of_Contemporary_Art__Boston_kr38w0.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-71.042857, 42.352843],
        },
    },
    {
        count: 28,
        title: 'Simmons Hall',
        architect: 'Steven Holl',
        year: 2002,
        address: '229 Vassar St, Cambridge, MA 02139',
        description: "The building has been nicknamed The Sponge, because the architect consciously modeled its shape and internal structure on a sea sponge. Opinions on the aesthetics of the building remain strongly divided. Simmons Hall won the 2003 American Institute of Architects Honor Award for Architecture, and the 2004 Harleston Parker Medal, administered by the Boston Society of Architects and awarded to the most beautiful piece of architecture building, monument or structure in the Boston area. Simmons Hall was featured in the exhibit Inside the Sponge—Students Take on MIT Simmons Hall at the Canadian Centre for Architecture in Montreal in the fall of 2006. On the other hand, the building has been criticized as being ugly, a sentiment echoed in James Kunstler's Eyesore of the Month catalog.",
        location: 'Boston',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648353239/attractions/c2bbda19964443.560416656dc18_slebek.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-71.09893172, 42.358176],
        },
    },
    {
        count: 29,
        title: 'Ray and Maria Stata Center',
        architect: 'Frank Gehry',
        year: 2004,
        address: '32 Vassar St, Cambridge, MA 02139',
        description: "The Ray and Maria Stata Center for Computer, Information and Intelligence Sciences is built on the site of MIT's legendary Building 20, a “temporary” timber-framed building constructed during World War II that served as a breeding ground for many great MIT-originated ideas. Designed by renowned architect Frank O. Gehry, the Stata Center is meant to carry on Building 20's innovative and serendipitous spirit, and to foster interaction and collaboration across many disciplines.",
        location: 'Boston',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648385780/attractions/mit-stata-center_pymtfq.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-71.090255, 42.36164],
        },
    },
    {
        count: 30,
        title: 'Boston Public Library Expansiion',
        architect: 'William Rawn Associates',
        year: 2012,
        address: '700 Boylston St, Boston, MA 02116',
        description: "Originally constructed in 1895, the library received an inward-facing addition in 1972. This renovation has dramatically transformed the second wing from a solid stone bunker to an inviting light-filled space that spills out into a newly defined public plaza. To honor the landmark building while redefining its use for a new era, the design team adhered to a set of core principles for preserving successful elements of the original beloved but outdated design. Increasing ceiling height and replacing dark-tinted glass and stone walls with floor-to-ceiling windows has completely opened the library interior to the city streets that surround the library on three sides.",
        location: 'Boston',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648386211/attractions/bpl-lampartners-exterior_frrplp.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-71.08574, 42.34939],
        },
    },
    {
        count: 31,
        title: 'Boston City Hall',
        architect: 'Kallmann McKinnell & Knowles',
        year: 1968,
        address: '1 City Hall Square Boston, MA',
        description: "The building has been subject to widespread public condemnation, and is sometimes called one of the world's ugliest buildings. Calls for the structure to be demolished have been regularly made even before construction was finished. Architects and critics considered it to be excellent work, with one poll finding that professional architects describe Boston City Hall as one of the ten proudest achievements of American architecture.",
        location: 'Boston',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648387176/attractions/boston-west-end-city-hal_660_232492593_pybigs.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-71.057967, 42.360322],
        },
    },
    {
        count: 32,
        title: 'V. C. Morris Gift Shop',
        architect: 'Frank Lloyd Wright',
        year: 1948,
        address: '155 Maiden Ln, San Francisco, CA 94108',
        description: "With its white, spiraling ramp, it is no surprise that the Xanadu Gallery was a predecessor of Frank Lloyd Wright Guggenheim Museum—it was designed by the architect some ten years earlier. This gallery is one of the few extant Wright retail spaces and his only design in San Francisco.",
        location: 'San Francisco',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648435179/attractions/3599688530_a2c947f69e_b_sdaz3e.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-122.4127071, 37.787576],
        },
    },
    {
        count: 33,
        title: 'Palace of Fine Arts',
        architect: 'William Gladstone Merchant',
        year: 1915,
        address: '3301 Lyon St, San Francisco, CA 94123',
        description: "Reminiscent of Roman ruins, the grand Palace of Fine Arts was designed by Bernard Maybeck for the purpose of displaying artworks during the Panama-Pacific International Exposition. Though most PPIE structures were torn down after the fair, the public deemed the palace, with its soaring colonnade and august rotunda, too beautiful to destroy. It now operates as a theater.",
        location: 'San Francisco',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648435242/attractions/1920px-Palace_of_Fine_Arts__16794p_l21mwt.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-122.448333, 37.802778],
        },
    },
    {
        count: 34,
        title: 'De Young Museum',
        architect: 'Jacques Herzog, Pierre de Meuron',
        year: 2005,
        address: '50 Hagiwara Tea Garden Dr, San Francisco, CA 94118',
        description: "The current building was completed by architects Jacques Herzog, Pierre de Meuron and Fong + Chan and opened on October 15, 2005. Structural, civil and geotechnical engineering was provided by Rutherford & Chekene; Arup provided mechanical and electrical engineering. Herzog & de Meuron won the competition in January 1999 beating out other short-listed architects Tadao Ando and Antoine Predock. The terrain and seismic activity in San Francisco posed a challenge for the designers Herzog & de Meuron and principal architects Fong & Chan. To help withstand future earthquakes, the building can move up to three feet (91 centimeters) due to a system of ball-bearing sliding plates and viscous fluid dampers that absorb kinetic energy and convert it to heat.]",
        location: 'San Francisco',
        images: [{
            url: 'https://res.cloudinary.com/madsky/image/upload/v1648436352/attractions/original_6a997324820480158bd84f366d0c2564_nknvhy.webp',
            filename: '1',
        }],
        author: '623a930c6ce69b95e4aaf10f',
        geometry: {
            type: 'Point',
            coordinates: [-122.4683501, 37.7716917],
        },
    },
]

